download:
  url:      https://github.com/des-science/mw-sats
  release:  v0.1
  filename: mw-sats-data.tar.gz

datadir : './data'
des:
  model   : 'classifier_stellar_des_v12.2.0.model'
  mask    : 'healpix_mask_des_v4.1.fits.gz'
  density : 'des_stellar_density_r22_equ_n128_v0.fits'
ps1: 
  model   : 'classifier_stellar_ps1_v13.0.1.model'
  mask    : 'healpix_mask_ps1_v4.1.fits.gz'
  density : 'ps1_stellar_density_r22_equ_n128_v0.fits'
maskbits : 
    GOOD :  0b0000000 # No flags 
    EBV  :  0b0000001 # E(B-V) > 0.2
    ASSOC:  0b0000010 # near object in catalogs (excluding known dwarfs)
    DWARF:  0b0000100 # near known dwarf 
    STAR :  0b0001000 # near bright star
    FOOT :  0b0010000 # outside of footprint             
    FAIL :  0b0100000 # location of failure in ugali PS1 processing
    ART  :  0b1000000 # location of artifact in PS1 footprint